%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Map_EOF_z500_SAT_SIC_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
EOF_code_run_annual_seasonal_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Regression_spatial_ERA_I_Z500_SAT_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
RICE_d18O_anomaly_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ASL_plot_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ERA_I_RI_corr_regress_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
HadISST_RI_corr_annual_seasonal_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

composite_SAM_PSA1_in_phase_ERA_I_z500_2mT_HadISST_SIC_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SAT_SIC_z500_RICE_DE22
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%