% Compute scalogram
% Scalogram_script_RI_d18O_DE21_c1.m
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 08-Nov-2021 12:00:38

clear
close all
tic
alt_nr=2;%%%%[1,2,4]%%%

if alt_nr==1
    load('C:\Users\Machine\matlab_storage_of_output_files\RI_combined_Deep_1213B_annual_means_no_summer_AMJJASON_c24.mat'); % AMJJASON
    title_str='d18O';
    letter='b';
elseif alt_nr==2
    load('C:\Users\Machine\matlab_storage_of_output_files\ERA-Interim_PCs_z500_lim0-360_-20_-90_1979-2011_AMJJASON_c52_annual_mean_varimax_c2.mat');  % AMJJASON
    title_str='SAM';
     letter='c';
elseif alt_nr==3
    load('SAM_NOAA_2.mat')
    title_str='SAM NOAA';
    %SAM_x=nanmean(SAM_NOAA_2,2);% annual means
    SAM_x=nanmean(SAM_NOAA_2(:,(4:11)),2);% AMJJASON means
    SAM_time=[1979:2015]';
    y_c=SAM_x(1:33);
     letter='';
elseif alt_nr==4
    load('C:\Users\Machine\matlab_storage_of_output_files\ERA-Interim_PCs_z500_lim0-360_-20_-90_1979-2011_AMJJASON_c52_annual_mean_varimax_c2.mat');  % AMJJASON
    title_str='PSA1';
    letter='d'; 
end


if alt_nr==1
    title_str_c='{\delta}^1^8O';
else
    title_str_c=title_str;
end


if alt_nr==1
    wr_c_ROI = MA_save(1980:2011,3);
elseif alt_nr==2 %SAM EOF
    wr_c_ROI =MA_PCs_save(:,2);
elseif alt_nr==3   
    wr_c_ROI=y_c;
elseif alt_nr==4
    wr_c_ROI =MA_PCs_save(:,3);
end





% Parameters
frequencyLimits = [0 1]; % Normalized frequency (*pi rad/sample)
voicesPerOctave = 8;


% title_str='d18O';

%
% Index into signal time region of interest
% timeLimits = [1 32]; % samples

% wr_c_ROI = MA_save(1901:2011,3);

timeLimits = [1 32]; % samples
wr_c_ROI_ROI = wr_c_ROI(:);
wr_c_ROI_ROI = wr_c_ROI_ROI(timeLimits(1):timeLimits(2));


%
% Convert to cycles/samples
frequencyLimits =frequencyLimits/2;

% continuous wavelet transform
% Limit the cwt frequency limits
frequencyLimits(1) = max(frequencyLimits(1),...
    cwtfreqbounds(numel(wr_c_ROI_ROI)));


% Compute cwt
% Run the function call below without output arguments to plot the results
[WT,F] = cwt(wr_c_ROI_ROI, ...
    'VoicesPerOctave',voicesPerOctave, ...
    'FrequencyLimits',frequencyLimits);



f1=fig('units','inches','width',11.5,'height',7.5,'font','Helvetica','fontsize',18,'border','on');
   box on
cwt(wr_c_ROI_ROI, ...
    'VoicesPerOctave',voicesPerOctave, ...
    'FrequencyLimits',frequencyLimits);
hold on
xlabel('Year')
yrs=[1979:2011]';
%xticks([0 20 40 60 80 100])
xticks([0 10 20 30])
% time_ROI = MA_save(1901:2011,1);
 title(['Magnitude Scalogram ',title_str_c])
% xticklabels({num2str(time_ROI(1)),num2str(time_ROI(21)),num2str(time_ROI(41)),num2str(time_ROI(61)),num2str(time_ROI(80)),num2str(time_ROI(101)) })
xticklabels({num2str(yrs(1)),num2str(yrs(12)),num2str(yrs(22)),num2str(yrs(32))})
%
                 set(gca,...
          'linewidth',3,...
          'FontWeight','bold' ); 

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
 %letter='a';
 
 %letter_position=   [240 380 60 60];
 letter_position=   [30 620 50 60];
          TextBox = uicontrol('style','text');
          set(TextBox,'String',letter,'position',letter_position,'FontSize',36,'FontWeight','bold'); % x position y position xsize ysize ,'FontWeight','bold'
          set(TextBox,'foregroundcolor', [0 0 0], ...
         'backgroundcolor', [1 1 1]);
         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% save fig

save_fig=1;
if save_fig==1
    site='RI';
    filename=['CWT_',site,'_',title_str];
    filedir ='C:\Users\Machine\matlab_storage_of_output_files\figures\';
    savefilename_c=strcat(filedir,filename);

    % save as png 
    orient landscape
    cd('G:\My Drive\ISO_CFA\matlab')
    export_fig('-png','-painters', '-depsc','-opengl', '-r190',savefilename_c);  % ,'-nocrop'         
    export_fig('-pdf','-painters', '-depsc','-opengl', '-r190',savefilename_c);  % ,'-nocrop'
    cd('G:\My Drive\ClimDyn_oct2022_R4\ClimDyn_R4_2022_Matlab\ClimDyn_R4_2022_Matlab')  
end 

toc